/*
==========================================================
PROJECT : Sales Performance & Customer Insights
DATABASE: Sales_Analytics

15 CORE SQL BUSINESS QUERIES

Purpose:
Analyze revenue, profitability, customers, products,
regions, sales representatives, and business trends.

SQL Skills Covered:
- Aggregation
- GROUP BY / ORDER BY
- JOINs through analytical view
- CASE WHEN
- Subqueries
- CTEs
- Window Functions
- Date Functions
==========================================================
*/

USE Sales_Analytics;


/* ============================================================
   QUERY 01: TOTAL REVENUE
   ------------------------------------------------------------
   WHY:
   Measure the company's overall sales revenue after discounts.

   SQL CONCEPT:
   SUM() aggregation
   ============================================================ */

SELECT
    ROUND(SUM(NetSales), 2) AS TotalRevenue
FROM vw_sales;


/* ============================================================
   QUERY 02: TOTAL PROFIT
   ------------------------------------------------------------
   WHY:
   Measure the total profit generated by the business.

   SQL CONCEPT:
   SUM() aggregation
   ============================================================ */

SELECT
    ROUND(SUM(Profit), 2) AS TotalProfit
FROM vw_sales;


/* ============================================================
   QUERY 03: PROFIT MARGIN %
   ------------------------------------------------------------
   WHY:
   Measure how efficiently revenue is converted into profit.

   Formula:
   Profit Margin = Profit / Revenue × 100

   SQL CONCEPT:
   Aggregation + calculated metric
   ============================================================ */

SELECT
    ROUND(
        SUM(Profit) / NULLIF(SUM(NetSales), 0) * 100,
        2
    ) AS ProfitMarginPercent
FROM vw_sales;


/* ============================================================
   QUERY 04: TOTAL ORDERS & CUSTOMERS
   ------------------------------------------------------------
   WHY:
   Measure the overall order volume and customer reach.

   SQL CONCEPT:
   COUNT(DISTINCT)
   ============================================================ */

SELECT
    COUNT(DISTINCT OrderID) AS TotalOrders,
    COUNT(DISTINCT CustomerID) AS TotalCustomers
FROM vw_sales;


/* ============================================================
   QUERY 05: AVERAGE ORDER VALUE (AOV)
   ------------------------------------------------------------
   WHY:
   Understand the average revenue generated from each order.

   Approach:
   First calculate revenue at order level, then calculate
   the average across all orders.

   SQL CONCEPT:
   Subquery + GROUP BY + AVG()
   ============================================================ */

SELECT
    ROUND(AVG(OrderRevenue), 2) AS AverageOrderValue
FROM (
    SELECT
        OrderID,
        SUM(NetSales) AS OrderRevenue
    FROM vw_sales
    GROUP BY OrderID
) AS order_summary;


/* ============================================================
   QUERY 06: MONTHLY REVENUE TREND
   ------------------------------------------------------------
   WHY:
   Track revenue performance over time and identify
   high- and low-performing months.

   SQL CONCEPT:
   DATE_FORMAT() + GROUP BY
   ============================================================ */

SELECT
    DATE_FORMAT(OrderDate, '%Y-%m') AS Month,
    ROUND(SUM(NetSales), 2) AS Revenue
FROM vw_sales
GROUP BY DATE_FORMAT(OrderDate, '%Y-%m')
ORDER BY Month;


/* ============================================================
   QUERY 07: TOP 10 PRODUCTS BY REVENUE
   ------------------------------------------------------------
   WHY:
   Identify the products contributing the most revenue
   and understand their profitability.

   SQL CONCEPT:
   GROUP BY + ORDER BY + LIMIT
   ============================================================ */

SELECT
    ProductName,
    ROUND(SUM(NetSales), 2) AS Revenue,
    SUM(Quantity) AS UnitsSold,
    ROUND(SUM(Profit), 2) AS Profit
FROM vw_sales
GROUP BY ProductName
ORDER BY Revenue DESC
LIMIT 10;


/* ============================================================
   QUERY 08: REVENUE & PROFIT BY CATEGORY
   ------------------------------------------------------------
   WHY:
   Compare product categories based on revenue, profit,
   units sold, and profitability.

   SQL CONCEPT:
   GROUP BY + calculated metric
   ============================================================ */

SELECT
    Category,
    ROUND(SUM(NetSales), 2) AS Revenue,
    ROUND(SUM(Profit), 2) AS Profit,
    ROUND(
        SUM(Profit) / NULLIF(SUM(NetSales), 0) * 100,
        2
    ) AS ProfitMarginPercent,
    SUM(Quantity) AS UnitsSold
FROM vw_sales
GROUP BY Category
ORDER BY Revenue DESC;


/* ============================================================
   QUERY 09: TOP 10 CUSTOMERS BY REVENUE
   ------------------------------------------------------------
   WHY:
   Identify high-value customers who contribute significantly
   to business revenue.

   SQL CONCEPT:
   GROUP BY + COUNT(DISTINCT) + ORDER BY
   ============================================================ */

SELECT
    CustomerID,
    CONCAT(FirstName, ' ', LastName) AS CustomerName,
    ROUND(SUM(NetSales), 2) AS Revenue,
    COUNT(DISTINCT OrderID) AS Orders,
    ROUND(SUM(Profit), 2) AS Profit
FROM vw_sales
GROUP BY
    CustomerID,
    FirstName,
    LastName
ORDER BY Revenue DESC
LIMIT 10;


/* ============================================================
   QUERY 10: REVENUE BY CUSTOMER AGE GROUP
   ------------------------------------------------------------
   WHY:
   Understand which customer age segments contribute the
   most revenue.

   SQL CONCEPT:
   CASE WHEN + GROUP BY
   ============================================================ */

SELECT
    CASE
        WHEN Age BETWEEN 18 AND 25 THEN '18-25'
        WHEN Age BETWEEN 26 AND 35 THEN '26-35'
        WHEN Age BETWEEN 36 AND 45 THEN '36-45'
        WHEN Age BETWEEN 46 AND 55 THEN '46-55'
        ELSE '55+'
    END AS AgeGroup,

    ROUND(SUM(NetSales), 2) AS Revenue,
    COUNT(DISTINCT CustomerID) AS Customers,
    COUNT(DISTINCT OrderID) AS Orders

FROM vw_sales

GROUP BY
    CASE
        WHEN Age BETWEEN 18 AND 25 THEN '18-25'
        WHEN Age BETWEEN 26 AND 35 THEN '26-35'
        WHEN Age BETWEEN 36 AND 45 THEN '36-45'
        WHEN Age BETWEEN 46 AND 55 THEN '46-55'
        ELSE '55+'
    END

ORDER BY Revenue DESC;


/* ============================================================
   QUERY 11: REVENUE & PROFIT BY REGION
   ------------------------------------------------------------
   WHY:
   Compare regional performance and identify the strongest
   markets for sales and profitability.

   SQL CONCEPT:
   GROUP BY + multiple KPIs
   ============================================================ */

SELECT
    RegionName,
    ROUND(SUM(NetSales), 2) AS Revenue,
    ROUND(SUM(Profit), 2) AS Profit,
    COUNT(DISTINCT OrderID) AS Orders,
    COUNT(DISTINCT CustomerID) AS Customers
FROM vw_sales
GROUP BY RegionName
ORDER BY Revenue DESC;


/* ============================================================
   QUERY 12: TOP 10 SALES REPRESENTATIVES
   ------------------------------------------------------------
   WHY:
   Identify the highest-performing sales representatives
   based on revenue and profit contribution.

   SQL CONCEPT:
   GROUP BY + multiple aggregations
   ============================================================ */

SELECT
    RepName,
    ROUND(SUM(NetSales), 2) AS Revenue,
    ROUND(SUM(Profit), 2) AS Profit,
    COUNT(DISTINCT OrderID) AS OrdersHandled,
    COUNT(DISTINCT CustomerID) AS CustomersServed
FROM vw_sales
GROUP BY RepName
ORDER BY Revenue DESC
LIMIT 10;


/* ============================================================
   QUERY 13: TOP PRODUCT IN EACH CATEGORY
   ------------------------------------------------------------
   WHY:
   Identify the best-performing product within every
   product category.

   SQL CONCEPT:
   CTE + ROW_NUMBER() window function
   ============================================================ */

WITH product_revenue AS (

    SELECT
        Category,
        ProductName,
        SUM(NetSales) AS Revenue,

        ROW_NUMBER() OVER (
            PARTITION BY Category
            ORDER BY SUM(NetSales) DESC
        ) AS ProductRank

    FROM vw_sales

    GROUP BY
        Category,
        ProductName
)

SELECT
    Category,
    ProductName,
    ROUND(Revenue, 2) AS Revenue
FROM product_revenue
WHERE ProductRank = 1
ORDER BY Category;


/* ============================================================
   QUERY 14: RUNNING MONTHLY REVENUE
   ------------------------------------------------------------
   WHY:
   Track cumulative revenue growth throughout the period.

   SQL CONCEPT:
   CTE + SUM() OVER() window function
   ============================================================ */

WITH monthly_revenue AS (

    SELECT
        DATE_FORMAT(OrderDate, '%Y-%m') AS Month,
        SUM(NetSales) AS Revenue

    FROM vw_sales

    GROUP BY DATE_FORMAT(OrderDate, '%Y-%m')
)

SELECT
    Month,
    ROUND(Revenue, 2) AS Revenue,

    ROUND(
        SUM(Revenue) OVER (
            ORDER BY Month
        ),
        2
    ) AS RunningRevenue

FROM monthly_revenue
ORDER BY Month;


/* ============================================================
   QUERY 15: CATEGORY REVENUE CONTRIBUTION
   ------------------------------------------------------------
   WHY:
   Understand how much each category contributes to
   the company's total revenue.

   SQL CONCEPT:
   CTE + Window Function
   ============================================================ */

WITH category_revenue AS (

    SELECT
        Category,
        SUM(NetSales) AS Revenue

    FROM vw_sales

    GROUP BY Category
)

SELECT
    Category,
    ROUND(Revenue, 2) AS Revenue,

    ROUND(
        Revenue * 100.0 /
        NULLIF(SUM(Revenue) OVER (), 0),
        2
    ) AS RevenueContributionPercent

FROM category_revenue
ORDER BY Revenue DESC;